config/routes.rb
Blog::Application.routes.draw do

  resources :posts, :only => [:show, :index]

namespace :admin do 
    resources :posts  
end

get '/admin' => 'admin/posts#index'

  get '/resources' => 'static_pages#resources'
  get '/experience' => 'static_pages#experience'
  root 'static_pages#home'
  

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	
	validates :title, presence: true, length: { minimum: 5 }
	validates :text, presence: true
	accepts_nested_attributes_for :category
end

app/controllers/admin/categories_controller.rb
# more comments
class Admin::CategoriesController < ApplicationController
def create
	@post = Post.find(params[:post_id])
 	@categories = @post.categories.create(params[:category].permit(:name))
	redirect_to post_path(@post)
end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
	http_basic_authenticate_with name: "sk", password: "Psalm139!", except: :index

	def index
		@post = Post.all
	end

	def new
		@post = Post.new

	end

#there is something wrong with my create action.... 
	def create 
		@post = Post.new(post_params)

		@post.save
		redirect_to admin_post_path@post 
	end

	def edit
		@post = Post.find(params[:id])
	end
	
	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to admin_post_path(@post)
		else
			render 'edit' 
		end
	end

	def show
		@post = Post.find(params[:id])
	end


	def destroy
		@post = Post.find(params[:id])
		@post.destroy 

		redirect_to admin_posts_path
	end


private
	def post_params
		params.require(:post).permit(:title, :text, categories_attributes: [:name])
	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def new
  end
end

app/controllers/application_controller.rb
# random comment
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@post = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<p> Copyright &copy; 2013 </p>



<!-- <div id="social_media">
	<ul> 

<li><%= link_to image_tag("twitter.png"), "http://www.twitter.com/sarahbkim", target: '_blank' %></li> 

<li> <%= link_to image_tag("github_alt.png"), "http://www.github.com/sarahbkim", target: '_blank' %></li> 

<li><%= link_to image_tag("google_plus.png"), "https://plus.google.com/117562047072478523775/posts", target: '_blank' %></li>

<li><%= link_to image_tag("linkedin.png"), "http://www.linkedin.com/pub/sarah-bo-hyun-kim/2a/38b/7bb", target: '_blank' %>
	</li>
</ul> 
</div> 

--> 

app/views/layouts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45402627-1', 'sarahbkim.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav id="nav">
	<ul>
		<li><%= link_to "HOME", root_path%></li>
		<li><%= link_to "EXPERIENCES", experience_path %> </li>
		<li><%= link_to "RESOURCES", resources_path %></li>
		<li><%= link_to "BLOG", "http://sarahbkim.com/blog" %> </li>
	</ul> 

	<%= image_tag "pointer-down.png", id: "pointer" %> 

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

 <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %> 


  <!-- FONTS --> 
<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>

<link href='http://fonts.googleapis.com/css?family=Bitter:400,700' rel='stylesheet' type='text/css'>

<%= csrf_meta_tag %>

 <!-- Javascript Stuff --> 

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

<!--[if !IE 7]>
	<style type="text/css">
		#wrap {display:table;height:100%}
	</style>
<![endif]-->

<!-- Google Analytics Tracking Code --> 
<%= render 'layouts/ga' %> 

<!-- Google Authorship --> 
<a href="https://plus.google.com/u/0/+sarahkim00/?
   rel=author">Google</a>

  <title><%= yield(:title) %></title>

</head>
<body>
	<div class="wrapper">

	<div id="header"> 
		<%= render 'layouts/header' %>
	</div>

	<div id="main"> 
		<%= image_tag "ME.jpg", size:"150x150", id: "header_img" %> 
		<%= yield %>
	</div>  

	<div id="footer"> 
	<%= render 'layouts/footer' %>
	</div>
		
</body>
</html>

app/views/posts/index.html.erb
<% provide(:title, 'Blog | S:K') %> 

<section id="intro">  
<% @post.each do |post| %> 
<h2><%= post.title %> </h2>
<p id="cate_tag">
<%= image_tag "posts_category.png", id: "cate_img" %>category 1, category 2</p>
<p>
<%= raw post.text %><br>

<%= link_to "Continue", post, id: "right" %>

</p>
<% end %> 
</section> 

app/views/posts/show.html.erb
<section id='intro'> 
	<h2><%= @post.title %></h2><br>
	<p><%= raw @post.text %> <br>
 <p id="cate_tag"><%= image_tag "posts_category.png", id: "cate_img" %>category 1, category 2</p><br>
 
<%= link_to image_tag('pointer-left.png'), blog_path, id: "left" %>
<%= link_to image_tag('pointer-right.png'), blog_path, id: "right" %>

<!-- disqus comments --> 
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'sarahbkim'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

</p>
</section>

app/views/static_pages/experience.html.erb
<% provide(:title, 'Experiences | S:K') %> 


<section id='intro'> 

		<h1>Experiences</h1>

		<p> 
			I've just built <strong>this website and blog</strong> from scratch <em>(Can you still say you built something from scratch when you've used Rails? Granted, I didn't use scaffolding but Rails does so much work for you from the get-go).</em>
			<br></br>

			Future projects include: solving the problem of uncomfortable shoes, a book club app, and an integrated search engine for medieval manuscripts. <em>(What can I say? It was the most annoying aspect of being a scholar. Just because we studied the Middle Ages didn't mean we had to work like we lived in 13th century).</em> Of course, I must also continue to fill the gaping holes of my <%=link_to 'CS knowledge', '/resources' %> and document the <%=link_to 'process', '/blog' %>.

			<br></br>

			<h2>Online Marketing Coordinator</h2>

			<p>
			Did some stuff with excel, SEO, and Google Analytics
			</p>
			<br>

			<h2>Graduate Student at Oxford University</h2> 
			<p>
			Looked at some super old manuscripts. Touched them too.
			</p>
			<br>

			<h2>History Student at UC Berkeley</h2> 
			<p>
			Studied a lot. Took on some side jobs as well.
			</p>
			<br>
</section> 

app/views/static_pages/home.html.erb
<% provide(:title, 'Home | S:K') %> 
<section id="intro"> 
		<h1>About</h1>
		<p>
I’m an aspiring hacker with a rather random background in Medieval Studies. I spent a few years communing with dead societies (history major) and looking at very old books made of cowhide <%=link_to "(like this one)", "http://auchinleck.nls.uk/", :target => '_blank' %>. <br></br> 

Oxford was a bit too cold and the idea of pursuing an esoteric subject for the rest of my life was a bit dreary.<br></br> 

So, back in the SF Bay Area, I’ve a masochistic tendency to supplement full-time work with rest-of-the-time-learning-to-code. 
<br></br> 

And the rest, I guess, is <%=link_to "history", '/experience' %>.
<br></br>

</section>

app/views/static_pages/resources.html.erb
<% provide(:title, 'Resources | S:K') %> 


<section id='intro'> 

		<h1>Resources</h1> 
		
		<p>
			The internet is a magical place where a lot of information is free for the taking. During my (now) ten-month foray into the world of computer science, I've found the following resources valuable.<br></br> 

			Also, I'd recommend local meetups that provide training, lectures, and tutorials. CS friends have also been a wonderful resource along with my foremost teacher: <%=link_to "Google", "www.google.com", :target => "_blank" %>
		</p>
		<br></br>

		<h2>CS Basics/ Foundations</h2>
			<p>
				<%= link_to "UC Berkeley's CS 61A Course", "http://www-inst.eecs.berkeley.edu/~cs61a/sp13/", :target => "_blank" %> Although I've tried to learn from Codeacademy before, it was only by going through an introductory course on CS that I started understanding the basics. Go through all the homeworks and labs at least!<br>
				<%= link_to "CS 61A Lectures on Youtube", "http://www.youtube.com/watch?v=QMV45tHCYNI", :target => "_blank" %><br>
			</p>
					<br></br>

		<h2>HTML/CSS/JS</h2> 
			<p>
				<%= link_to "Codeacademy", "http://www.codecademy.com/", :target => "_blank" %> I still found Codeacademy useful for learning the syntax of different coding languages as well as for immediate gratification. However, like reading (most) medieval latin texts v.s. classical, you may delude yourself into thinking you comprehend more than you actually do.<br>
				<%= link_to "Mozilla Developer Network's CSS Help", "https://developer.mozilla.org/en-US/docs/Web/CSS", :target => "_blank" %><br>
				<%= link_to "Eloquent Javascript", "http://eloquentjavascript.net/", :target => '_blank' %><br>
			</p> 
					<br></br>

		<h2>Ruby</h2>
			<p>
				<%= link_to "The Well-Grounded Rubyist", "http://www.amazon.com/gp/product/1933988657", :target => "_blank" %><br>
				<%= link_to "Eloquent Ruby", '#', :target => '_blank' %> There are a number of wonderful Ruby Resources out there. I think these two books, however, provide a good, solid introduction. As much as I love Why's Poignant Guide ("Chunky Bacon! Chunky Bacon!), his rather stream-of-consciousness style was distracting.<br>
			</p>
		<br></br>

		<h2>Ruby on Rails</h2>
			<p>
				<%= link_to "Hartl\'s Rails Tutorial", "http://ruby.railstutorial.org/ruby-on-rails-tutorial-book#top", :target => '_blank' %> Go through this tutorial. Just do it.</br>
				<%= link_to 'Ruby on Rails Guides', 'http://guides.rubyonrails.org/', :target => '_blank' %>During/After going through Hartl, make sure you understand the fundamentals (like MVC!)</br>
			</p>	
		<br></br>

		<h2>Git</h2> 
			<p>
				<%= link_to "Understanding Git Conceptually", "http://www.sbf5.com/~cduan/technical/git/", :target => "_blank" %><br>			
				<em> Hartl's Rails Tutorial gives a great &amp; practical introduction to Git, Heroku, and test-driven development</em><br>
			</p>

</section> 